GET http://localhost:3001/api/threads/newest20

###

POST http://localhost:3001/api/threads
Content-Type: application/json

{
    "title": "Hello title!"
}

###

POST http://localhost:3001/api/threads/new-thread-with-message
Content-Type: application/json

{
    "title": "Thread with a message 2",
    "text": "This is the message part of the thread 2."
}

###

POST http://localhost:3001/api/message
Content-Type: application/json

{
    "thread_id": 22,
    "text": "Message for some thread 2."
}

###

GET http://localhost:3001/api/threads/22